### PR TITLE
Update image crate to 0.24

### PR DESCRIPTION
**Pull request by emilk**

### CODE REVIEW

**Review by Jasper-Bekkers — APPROVED** [review]
We ran into this as well.

**Comment by complexspaces** [comment]
Hey everyone, sorry for the delay reviewing this. I've been on leave for a few weeks.

It looks like the API of `image` changed in `0.24` and its breaking the Linux builds. Do you have access to a Linux system to look at the problem?

**Comment by emilk** [comment]
@complexspaces I don't, but I tried my best anyway :)

**Review by complexspaces — APPROVED** [review]

**Comment by complexspaces** [comment]
Hey again @emilk. I decided to release this one on its own (I released 3.0 without it because we're stuck on `image 0.23` internally at work) and sadly got into a state of conflict. I fixed it locally but I wasn't able to update the PR branch. It's a pretty easy conflict, `num-iter` just needs removed from the lockfile.

As soon as the branch has the conflicts resolved, I'll merge this and release a version for you with the update :)

**Comment by emilk** [comment]
Done!

**Comment by complexspaces** [comment]
This is now released as `3.1.0`. Thanks for working with me on this one.

**Comment by emilk** [comment]
Thanks!

**Pull request merged**
