### PR TITLE
Update image to 0.25

### PR DESCRIPTION
**Pull request by torokati44**
This should help with https://github.com/emilk/egui/pull/4160.
(High five, @ArturKovacs! :grinning: )

### CODE REVIEW

**Comment by torokati44** [comment]
It's been a while, so ... bump? :flushed:

**Review by complexspaces — CHANGES_REQUESTED** [review]
Sorry for the delay getting to this one. Thank you for the update here.

The current set of changes looks good, but it seems like some API changes are required? I'm happy to approve and merge this once those fixes are made.

**Comment by torokati44** [comment]
Ah, yes, now that CI was finally allowed to run, I can see that... 😅
Sure, could also have checked locally... 😶🙄
I'll get on fixing it in an hour or two!

**Comment by complexspaces** [comment]
Sorry about that bad feedback cycle with CI 😓. Please don't feel any need to rush fixing this.

**Comment by torokati44** [comment]
No worries, it's fine! ^^

Though, the fact that apparently _every single_ CI run needs to be approved manually, _and_ it's in fail-fast mode, might drag this out a little bit more. I'm in no rush though!

**Review by complexspaces — APPROVED** [review]

**Comment by torokati44** [comment]
Thank you for the merge! :partying_face: 
Now we only have to wait for a new release... :eyes: :pray:

**Comment by complexspaces** [comment]
I have not forgotten about this one 😓. I am hoping to make some other tweaks this weekend before making a new minor release.

**Comment by torokati44** [comment]
Ooh, amazing! 😊 That's fairly soon! Thank you!

**Comment by complexspaces** [comment]
This is now released in version [3.4.0](https://github.com/1Password/arboard/releases/tag/v3.4.0) on crates.io. Thanks for your patience.

**Pull request merged**
