### PR TITLE
Add timeout for RustConnection::connect to X11 server

### PR DESCRIPTION
**Pull request by jonZlotnik**
Should fail if we can't make a connection instead of hanging on the X11 socket

I encountered this in environments like the vscode terminal into WSL2 where the connection never gets made, and the OS never responds.

### CODE REVIEW

**Comment by jonZlotnik** [comment]
here's the call stack when it get's stuck:

image

**Comment by jonZlotnik** [comment]
@complexspaces could I get a quick review?
it's a ~10 liner 🙂

**Comment by complexspaces** [comment]
Hey there, @jonZlotnik,

I did take a preliminary look at this, but I got a bit lost in the weeds trying to see if there was a better way to implement the timeout. My apologies. 

In general I think that I'm fine with this change but I'm a little concerned that the non-obvious strategy could lead to a bunch of hung OS threads in someone's app in situations like your own, or over the network, if the user of `arboard` has implemented their own retry loop. AFAICT though, there is no way to set a timeout for connecting to a blocking UNIX socket, leaving this solution here. Does that sound about right to you as well>

**Comment by jonZlotnik** [comment]
> I did take a preliminary look at this, but I got a bit lost in the weeds trying to see if there was a better way to implement the timeout. My apologies.

No worries. I'm glad we came to the same conclusion.

> In general I think that I'm fine with this change but I'm a little concerned that the non-obvious strategy could lead to a bunch of hung OS threads in someone's app in situations like your own, or over the network, if the user of `arboard` has implemented their own retry loop.

I thought about this too. I think this is the abstraction level in which to have the timeout because the underlying OS dependencies are most obvious here. I don't think user app devs necessarily consider handling the clipboard like a socket.

I could try to to implement some kind of singleton pattern, but if the retry loop is meant to deal with some other error case then we'd be messing up their retry logic.

Overall, I think a few loose threads are okay. And it's not like they're storing MBs of state.

**Comment by complexspaces** [comment]
Once this is passing CI, I'm happy to approve it and merge. It just looks like a few linter errors now.

**Comment by jonZlotnik** [comment]
Oh weird, clippy passes on windows but not on ubuntu

Windows commit 45b32bec071b70678e05688bdf203ab5ed1b8fa7
```
# cargo clippy --verbose --no-default-features -- -D warnings -D clippy::dbg_macro                            Fresh unicode-ident v1.0.4
       Fresh str-buf v1.0.6
       Fresh cfg-if v1.0.0
       Fresh proc-macro2 v1.0.43
       Fresh quote v1.0.21
       Fresh libc v0.2.133
       Fresh winapi v0.3.9
       Fresh log v0.4.17
       Fresh syn v1.0.100
       Fresh error-code v2.3.1
       Fresh thiserror-impl v1.0.35
       Fresh clipboard-win v4.4.2
       Fresh thiserror v1.0.35
       Fresh arboard v3.2.0 (C:\Users\jzlot\Repos\jonZlotnik\arboard)
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
```
Ubuntu commit 45b32bec071b70678e05688bdf203ab5ed1b8fa7
```
➜  arboard git:(timeout-for-x11-rustconnection) cargo clippy --verbose --no-default-features -- -D warnings -D clippy::dbg_macro
       Fresh autocfg v1.1.0
       Fresh cfg-if v1.0.0
       Fresh unicode-ident v1.0.4
       Fresh libc v0.2.133
       Fresh proc-macro2 v1.0.43
       Fresh quote v1.0.21
       Fresh memoffset v0.6.5
       Fresh bitflags v1.3.2
       Fresh nix v0.24.2
       Fresh syn v1.0.100
       Fresh smallvec v1.9.0
       Fresh scopeguard v1.1.0
       Fresh parking_lot_core v0.9.3
       Fresh lock_api v0.4.9
       Fresh thiserror-impl v1.0.35
       Fresh x11rb-protocol v0.10.0
       Fresh gethostname v0.2.3
       Fresh parking_lot v0.12.1
       Fresh thiserror v1.0.35
       Fresh x11rb v0.10.1
       Fresh log v0.4.17
    Checking arboard v3.2.0 (/home/me/repos/jonZlotnik/arboard)
     Running `/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/clippy-driver rustc --crate-name arboard --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=120 --crate-type lib --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 -C metadata=99044b3871657063 -C extra-filename=-99044b3871657063 --out-dir /home/me/repos/jonZlotnik/arboard/target/debug/deps -C incremental=/home/me/repos/jonZlotnik/arboard/target/debug/incremental -L dependency=/home/me/repos/jonZlotnik/arboard/target/debug/deps --extern log=/home/me/repos/jonZlotnik/arboard/target/debug/deps/liblog-9e35576f866246aa.rmeta --extern parking_lot=/home/me/repos/jonZlotnik/arboard/target/debug/deps/libparking_lot-dfdc8ffb4356146d.rmeta --extern thiserror=/home/me/repos/jonZlotnik/arboard/target/debug/deps/libthiserror-5b29ae76a17eb8ef.rmeta --extern x11rb=/home/me/repos/jonZlotnik/arboard/target/debug/deps/libx11rb-3c040bd011dc986d.rmeta`
error: unused import: `ConnectError`
  --> src/platform/linux/x11.rs:41:20
   |
41 |     rust_connection::{ConnectError, RustConnection},
   |                       ^^^^^^^^^^^^
   |
   = note: `-D unused-imports` implied by `-D warnings`

error: could not compile `arboard` due to previous error

Caused by:
  process didn't exit successfully: `/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/clippy-driver rustc --crate-name arboard --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=120 --crate-type lib --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 -C metadata=99044b3871657063 -C extra-filename=-99044b3871657063 --out-dir /home/me/repos/jonZlotnik/arboard/target/debug/deps -C incremental=/home/me/repos/jonZlotnik/arboard/target/debug/incremental -L dependency=/home/me/repos/jonZlotnik/arboard/target/debug/deps --extern log=/home/me/repos/jonZlotnik/arboard/target/debug/deps/liblog-9e35576f866246aa.rmeta --extern parking_lot=/home/me/repos/jonZlotnik/arboard/target/debug/deps/libparking_lot-dfdc8ffb4356146d.rmeta --extern thiserror=/home/me/repos/jonZlotnik/arboard/target/debug/deps/libthiserror-5b29ae76a17eb8ef.rmeta --extern x11rb=/home/me/repos/jonZlotnik/arboard/target/debug/deps/libx11rb-3c040bd011dc986d.rmeta` (exit status: 1)
```

**Comment by jonZlotnik** [comment]
@complexspaces Seems to be passing

**Review by complexspaces — APPROVED** [review]
Everything looks good now, thanks again for working on this!

**Comment by complexspaces** [comment]
These changes are now published in [version 3.2.1](https://crates.io/crates/arboard/3.2.1) on crates.io. I apologize for the delay getting to that.

**Pull request merged**
